site_name: My Docs

theme:
  name: material
  features:
    - content.code.copy


  font:
    text: Noto Sans JP
    code: Inconsolata

  palette:
    - scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  search:
    lang: "ja"

nav:
  - home: index.md
  - uvの設定:
      - uvのインストール: "1/1-1_uvのインストール.md"
      - uvの設定: "1/1-2_uvの設定.md"
  - カメラ画像の取得:
      - デプスとrgb画像の取得: "2/2-1_デプスとrgb画像の取得.md"
      - カメラ設定の変更: "2/2-2_カメラ設定の変更.md"
      - 複数台のカメラの接続: "2/2-3_複数台のカメラの接続.md"
  - GitHub:
      - GitHubの初期設定: "3/3-1_GitHubの初期設定.md"
